name: release

on:
  push:
    branches: [main, master]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3.0.2
    -
      name: Unshallow
      run: git fetch --prune --unshallow
    -
      uses: go-semantic-release/action@v1.18
      id: semantic
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        changelog-file: .changelog
