name: release

on:
  push:
    branches: [main, master]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    -
      name: Set up Go
      uses: actions/setup-go@v3
    -
      name: Create release tag
      uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    -
      run: git fetch -a && git pull
    -
      name: Release
      uses: goreleaser/goreleaser-action@v3
      with:
        version: latest
        args: release --config=.github/goreleaser.yml --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
